// export const pokemonType = {
//     normal: require('../assets/type/normal.png'),
//     fighting: require('../assets/type/fighting.png'),
//     flying: require('../assets/type/flying.png'),
//     poison: require('../assets/type/poison.png'),
//     ground: require('../assets/type/ground.png'),
//     rock: require('../assets/type/rock.png'),
//     bug: require('../assets/type/bug.png'),
//     ghost: require('../assets/type/ghost.png'),
//     steel: require('../assets/type/steel.png'),
//     fire: require('../assets/type/fire.png'),
//     water: require('../assets/type/water.png'),
//     grass: require('../assets/type/grass.png'),
//     electric: require('../assets/type/electric.png'),
//     psychic: require('../assets/type/psychic.png'),
//     ice:require('../assets/type/ice.png'),
//     dragon: require('../assets/type/dragon.png'),
//     dark: require('../assets/type/dark.png'),
//     fairy: require('../assets/type/fairy.png'),
// }
/* eslint-disable prettier/prettier */
export const pokemonTypes = {
    normal: require('../assets/type/normal.png'),
    fighting: require('../assets/type/fighting.png'),
    flying: require('../assets/type/flying.png'),
    poison: require('../assets/type/poison.png'),
    ground: require('../assets/type/ground.png'),
    rock: require('../assets/type/rock.png'),
    bug: require('../assets/type/bug.png'),
    ghost: require('../assets/type/ghost.png'),
    steel: require('../assets/type/steel.png'),
    fire: require('../assets/type/fire.png'),
    water: require('../assets/type/water.png'),
    grass: require('../assets/type/grass.png'),
    electric: require('../assets/type/electric.png'),
    psychic: require('../assets/type/psychic.png'),
    ice: require('../assets/type/ice.png'),
    dragon: require('../assets/type/dragon.png'),
    dark: require('../assets/type/dark.png'),
    fairy: require('../assets/type/fairy.png'),
  };